---
title: "Hot Hand Shooting"
author: "Andrew, Daniel, Rachel, Lily"
format: html
editor: visual
theme: lux
---

## Visualizing Bias (ft. Dr. Doi)

1.  Open this [shiny app](https://andrew-d-kerr.shinyapps.io/LongestRunHeads/).

2.  What is the P(Heads \| Heads)? In the long run, would you expect this value to be less then, approximately, or greater than 0.5? Why?

3.  Increase the number of repetitions to 1,000, what is the average value of P(H\|H)? Compare your results with the rest of the group, are they what you expected?

4.  What shape do you expect the distribution of P(H\|H) to take?

5.  Increase the number of repetition to 10,000. Is the shape what you expected?

6.  Refresh the page to clear your simulations. Try changing the probability of heads to a number of your choosing. What do you think the average P(H\|H) will be?

7.  Try running 1,000 trials with different P(H) values (remember to refresh the page before changing to clear the plots!). Are the values you are seeing what you expected?

8.  Set the probability of heads back to 0.5, check the box to "Show quantifying bias plot," and set the number of repetitions to 1,000. What do you notice?

9.  What do you think will happen to the shape of this graph as the number of trials decreases?

10. Try generating 1,000 repetitions with 10, 20, and 50 trials (you do not have to refresh the page between runs this time!). Was your intuition correct?

11. Will the same results hold true for different values of the probability of heads? Try running 1,000 repetitions with 50 trials at P(H) = 0.25 and 0.75. What do you notice?

## Permutations Test (ft. Dr. Ross)

1.  On first glance, which of these data sets appears to have evidence of a hot hand? Why? (Data is from 2016 NBA 3 point contest)

    Klay Thompson: 1,1,1,1,0,1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,1,0,0,0,1,1,0,1,0,1,0,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1

    Steph Curry: 0,0,0,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,1,0,1,1,1,0,0,1,0,1,1,0,1,1,0,1

    Devin Booker: 0,0,0,0,1,0,0,0,1,0,1,0,1,0,1,1,0,1,1,1,0,1,1,1,1,1,0,0,0,1,0,1,1,0,1,0,1,0,1

    Kevin Ross: 0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,0,0,0,1,1,1,1,1,0,0,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,1

2.  Run the data through this [shiny app](http://shiny.calpoly.sh/Hothand/). Set streak length to 3 and increase the number of shuffles to simulate to 100. Do the results match your intuition?

## Emergency Discussion Questions

If time allows, pick any discussion question(s) (pulled from the discussion board) that interest the group to dive into!

1.  Is it a better strategy to give the ball to the player with the most consistent scoring during that quarter or half, or past 5 games?
2.  How do you think the bias in the original hot hand paper stayed "hidden" for so long, especially considering there were many other papers published about the hot hand before the Miller and Sanjurjo paper corrected for the bias?
3.  Could there be other factors not being considered in these analyses that would provide evidence against the “hot hand” fallacy or further support the claims of the “hot hand” fallacy?
4.  Given that the GVT study influenced the perception of the hot hand for decades, what ethical responsibility do researchers have in making sure their statistical models are free from bias?
5.  From my personal experience (says Brandon), I always thought that the "hot hand" incorporates the fact that players tend to attempt more difficult shots after making streaks. I wonder if accounting for the difficultly of shots would lead to different results?
6.  What other sports have a similar phenomenon to "hot hands," or is this a special effect only in basketball?
7.  What was one good and one bad quality about any of the papers? For the good, why did you like this quality? For the bad, what do you think they could have done better/how would you have done it?
